import { ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, ClipboardList, MapPin, Target, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { Modal } from '../../components/ui/Modal';
import { PageHeader } from '../../components/ui/PageHeader';

const steps = ['1. Escopo', '2. Programação', '3. Revisão'];

export function NewOrderPage() {
  const [step, setStep] = useState(1);
  const [success, setSuccess] = useState(false);
  const navigate = useNavigate();
  return (
    <div className="order-form-page">
      <PageHeader title="Nova Ordem de Serviço" subtitle="Defina o escopo, programe a equipe e emita a atividade de campo." actions={<Link className="button button--ghost" to="/admin/orders"><ArrowLeft size={17} /> Voltar</Link>} />
      <div className="stepper">{steps.map((label, index) => <div className={`stepper__item ${step >= index + 1 ? 'active' : ''}`} key={label}><span>{step > index + 1 ? <Check size={16} /> : index + 1}</span><strong>{label}</strong></div>)}</div>
      <div className="order-form-layout">
        <section className="panel form-card">
          {step === 1 && <><div className="form-card__heading"><span><ClipboardList size={20} /></span><div><h2>Escopo da atividade</h2><p>Identifique onde e qual serviço será realizado.</p></div></div><div className="form-grid"><label className="span-2">Projeto<select defaultValue="solar"><option value="solar">Contrato O&M — Solaris Energia</option><option>Lavagem Preventiva — Lumina Power</option></select></label><label>Cliente<input defaultValue="Solaris Energia" /></label><label>UFV<select defaultValue="cerrado"><option value="cerrado">UFV Sol do Cerrado</option><option>UFV Boa Vista</option></select></label><label>Tipo de serviço<select defaultValue="rocagem"><option value="rocagem">Roçagem mecanizada</option><option>Lavagem de módulos</option><option>Inspeção visual</option></select></label><label>Área / setor<input defaultValue="Blocos B04 a B09" /></label><label className="span-2">Descrição<textarea defaultValue="Executar roçagem da vegetação entre as fileiras de módulos, preservando canaletas e sinalizações da UFV." /></label></div></>}
          {step === 2 && <><div className="form-card__heading"><span><CalendarDays size={20} /></span><div><h2>Programação e responsáveis</h2><p>Escolha data, equipe e parâmetros de produção.</p></div></div><div className="form-grid"><label>Data programada<input type="date" defaultValue="2026-08-27" /></label><label>Prazo de conclusão<input type="date" defaultValue="2026-08-27" /></label><label>Equipe<select defaultValue="norte"><option value="norte">Equipe Norte — Carlos Oliveira</option><option>Equipe Sul — Rafael Souza</option></select></label><label>Meta de produção<input defaultValue="16 hectares" /></label><label>Modelo operacional<select defaultValue="rocagem"><option value="rocagem">Checklist — Roçagem v3</option><option>Checklist — Lavagem v2</option></select></label><label>Prioridade<select defaultValue="normal"><option value="normal">Normal</option><option>Alta</option></select></label><label className="span-2 check-card"><input type="checkbox" defaultChecked /><span><strong>Exigir evidências georreferenciadas</strong><small>Fotos antes, durante e depois serão obrigatórias.</small></span></label></div></>}
          {step === 3 && <><div className="form-card__heading"><span><CheckCircle2 size={20} /></span><div><h2>Revisar e emitir</h2><p>Confira as informações que serão enviadas à equipe.</p></div></div><div className="review-grid"><div><MapPin size={18} /><span><small>Local de execução</small><strong>UFV Sol do Cerrado</strong><p>Blocos B04 a B09</p></span></div><div><ClipboardList size={18} /><span><small>Serviço</small><strong>Roçagem mecanizada</strong><p>Checklist — Roçagem v3</p></span></div><div><UsersRound size={18} /><span><small>Responsável</small><strong>Equipe Norte</strong><p>Carlos Oliveira · 6 integrantes</p></span></div><div><Target size={18} /><span><small>Planejamento</small><strong>27/08/2026</strong><p>Meta de 16 hectares</p></span></div></div><div className="emission-note"><CheckCircle2 size={19} /><span><strong>Pronta para emissão</strong><p>A OS ficará disponível no aplicativo da equipe e poderá ser executada mesmo sem sinal.</p></span></div></>}
          <footer className="form-actions">{step > 1 ? <Button variant="secondary" onClick={() => setStep(step - 1)}><ArrowLeft size={17} /> Voltar</Button> : <Link className="button button--secondary" to="/admin/orders">Cancelar</Link>}<Button onClick={() => step < 3 ? setStep(step + 1) : setSuccess(true)}>{step < 3 ? <>Continuar <ArrowRight size={17} /></> : <>Emitir Ordem de Serviço <Check size={17} /></>}</Button></footer>
        </section>
        <aside className="panel order-preview"><span className="eyebrow">PRÉVIA DA OS</span><h3>#2026-0155</h3><p>Roçagem mecanizada</p><div className="order-preview__map"><MapPin /><span>UFV Sol do Cerrado<small>Paracatu · MG</small></span></div><dl><div><dt>Cliente</dt><dd>Solaris Energia</dd></div><div><dt>Execução</dt><dd>27 ago. 2026</dd></div><div><dt>Equipe</dt><dd>{step > 1 ? 'Equipe Norte' : 'A definir'}</dd></div><div><dt>Meta</dt><dd>{step > 1 ? '16 hectares' : 'A definir'}</dd></div></dl><small className="preview-tip">Esta prévia é atualizada conforme o preenchimento.</small></aside>
      </div>
      <Modal open={success} onClose={() => setSuccess(false)} title="Ordem de Serviço emitida" footer={<><Button variant="secondary" onClick={() => navigate('/admin/orders')}>Ver todas as ordens</Button><Button onClick={() => navigate('/admin/orders/2026-0155')}>Abrir OS #0155</Button></>}><div className="success-modal"><span><CheckCircle2 size={28} /></span><h3>Atividade programada com sucesso</h3><p>A <strong>Equipe Norte</strong> receberá a OS #2026-0155 no aplicativo assim que o dispositivo estiver conectado.</p><div><Check size={16} /> Checklist e instruções incluídos</div><div><Check size={16} /> Evidências georreferenciadas obrigatórias</div></div></Modal>
    </div>
  );
}
