import { ArrowLeft, CalendarDays, ClipboardList, MapPin, Target, Tractor, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { MetricCard } from '../../components/ui/MetricCard';
import { PageHeader } from '../../components/ui/PageHeader';
import { orders, productionSeries } from '../../data/mockData';

export function ProjectDetailPage() {
  return <div><PageHeader title="UFV Sol do Cerrado" subtitle="Contrato O&M — Solaris Energia · Paracatu, MG" actions={<Link className="button button--secondary" to="/admin/projects"><ArrowLeft size={17} /> Projetos</Link>} /><section className="metrics-grid"><MetricCard label="Avanço contratual" value="72%" hint="144 de 200 hectares" icon={Target} /><MetricCard label="Ordens emitidas" value="24" hint="3 em andamento" icon={ClipboardList} tone="blue" /><MetricCard label="Equipes mobilizadas" value="2" hint="13 profissionais" icon={UsersRound} tone="violet" /><MetricCard label="Prazo contratual" value="126 dias" hint="Ago — Dez 2026" icon={CalendarDays} tone="orange" /></section><div className="project-detail-grid"><section className="panel"><div className="panel__header"><div><h2>Evolução da produção</h2><p>Hectares acumulados no contrato</p></div><span>144 / 200 ha</span></div><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><AreaChart data={productionSeries}><CartesianGrid vertical={false} stroke="#e8eee9" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="planned" stroke="#9ba9a1" fill="transparent" strokeDasharray="5 5" /><Area type="monotone" dataKey="actual" stroke="#168c43" fill="#eafbe8" strokeWidth={3} /></AreaChart></ResponsiveContainer></div></section><aside className="panel weekly-production"><div className="panel__header"><div><h2>Produção por equipe</h2><p>Últimos 7 dias</p></div></div><div><span className="avatar">EN</span><span><strong>Equipe Norte</strong><small>Carlos Oliveira · 6 profissionais</small></span><b>43,5 ha</b></div><div><span className="avatar">ES</span><span><strong>Equipe Sul</strong><small>Rafael Souza · 7 profissionais</small></span><b>37,2 ha</b></div><div className="weekly-total"><Tractor size={18} /><span>Total produzido na semana</span><strong>80,7 ha</strong></div></aside></div><section className="panel project-orders"><div className="panel__header"><div><h2>Ordens recentes</h2><p>Atividades vinculadas ao projeto</p></div><Link to="/admin/orders">Ver todas</Link></div>{orders.filter((o) => o.client === 'Solaris Energia').map((o) => <Link to={`/admin/orders/${o.id}`} key={o.id}><span><ClipboardList size={17} /></span><span><strong>OS #{o.id} · {o.service}</strong><small>{o.date} · {o.team}</small></span><b>{o.progress}%</b></Link>)}</section><section className="project-location panel"><MapPin /><span><small>LOCALIZAÇÃO DO PROJETO</small><strong>Rodovia MG-188, km 42 · Paracatu, Minas Gerais</strong></span></section></div>;
}
