import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, FileStack, Plus, UploadCloud } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../../components/ui/Button';
import { MetricCard } from '../../components/ui/MetricCard';
import { PageHeader } from '../../components/ui/PageHeader';
import { StatusBadge } from '../../components/ui/StatusBadge';

const recent = [['NF-e 000023781', 'NF-e', 'Hoje, 10:24', 'R$ 6.831,90', 'Pendente'], ['NFS-e 000003412', 'NFS-e', 'Ontem, 16:41', 'R$ 2.450,00', 'Concluído'], ['NF-e 000023764', 'NF-e', 'Ontem, 11:06', 'R$ 12.780,40', 'Concluído'], ['Declaração 08-2026', 'PDF', '22/08/2026', '—', 'Processando']] as const;
export function SupplierDashboardPage() { const navigate = useNavigate(); return <div className="supplier-dashboard"><PageHeader eyebrow="Portal do Fornecedor" title="Olá, Morganite Brasil" subtitle="Acompanhe os documentos enviados para a Allebras." actions={<Button icon={<Plus size={16} />} onClick={() => navigate('/fornecedor/enviar')}>Enviar novo documento</Button>} /><section className="supplier-metrics supplier-metrics--four"><MetricCard label="Documentos enviados" value="42" helper="Neste mês" icon={FileStack} tone="blue" /><MetricCard label="Concluídos" value="38" helper="90,4% do total" icon={CheckCircle2} tone="green" /><MetricCard label="Pendências" value="3" helper="Precisam da sua atenção" icon={AlertTriangle} tone="amber" /><MetricCard label="Processando" value="1" helper="Em validação pela Allebras" icon={Clock3} tone="cyan" /></section><section className="supplier-attention"><AlertTriangle size={21} /><div><strong>3 documentos precisam da sua atenção</strong><p>Complete as informações pendentes para que a Allebras possa concluir o processamento.</p></div><Button variant="secondary" size="sm" onClick={() => navigate('/fornecedor/pendencias')}>Ver pendências <ArrowRight size={14} /></Button></section><section className="card supplier-recent"><div className="card__header"><div><h2>Documentos recentes</h2><p>Últimos arquivos enviados pela Morganite Brasil</p></div><button onClick={() => navigate('/fornecedor/documentos')}>Ver todos <ArrowRight size={13} /></button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Documento</th><th>Tipo</th><th>Enviado em</th><th>Valor</th><th>Status</th></tr></thead><tbody>{recent.map(([document, type, date, value, status]) => <tr key={document}><td><strong>{document}</strong></td><td>{type}</td><td>{date}</td><td><strong>{value}</strong></td><td><StatusBadge status={status} /></td></tr>)}</tbody></table></div></section><section className="supplier-help card"><UploadCloud size={20} /><div><strong>Envio simples e seguro</strong><p>Seus documentos são validados e encaminhados automaticamente para a Allebras.</p></div><Button variant="ghost" size="sm" onClick={() => navigate('/fornecedor/enviar')}>Como funciona?</Button></section></div>; }
