import { Building2, ChevronDown, Ellipsis, FileCheck2, MailPlus, Plus, Search, UsersRound, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../../components/ui/Button';
import { MetricCard } from '../../components/ui/MetricCard';
import { PageHeader } from '../../components/ui/PageHeader';
import { StatusBadge } from '../../components/ui/StatusBadge';
import { suppliers } from '../../data/mockData';

export function SuppliersPage() {
  const [invite, setInvite] = useState(false);
  const [menu, setMenu] = useState<string | null>(null);
  return <div><PageHeader title="Fornecedores" subtitle="Gerencie empresas, acessos e o volume documental enviado à Allebras." actions={<Button icon={<Plus size={16} />} onClick={() => setInvite(true)}>Convidar fornecedor</Button>} /><section className="supplier-metrics"><MetricCard label="Fornecedores cadastrados" value="128" helper="8 adicionados neste mês" icon={Building2} tone="blue" /><MetricCard label="Acessos ativos" value="94" helper="73,4% dos fornecedores" icon={UsersRound} tone="green" /><MetricCard label="Pendências abertas" value="12" helper="5 empresas impactadas" icon={FileCheck2} tone="amber" /></section><section className="secondary-toolbar card"><label><Search size={15} /><input placeholder="Buscar empresa, CNPJ ou contato..." /></label><button>Status<ChevronDown size={13} /></button></section><section className="data-card"><div className="table-scroll"><table className="data-table suppliers-table"><thead><tr><th>Empresa</th><th>CNPJ</th><th>Contato</th><th>Documentos</th><th>Pendências</th><th>Último envio</th><th>Status</th><th /></tr></thead><tbody>{suppliers.map((supplier) => <tr key={supplier.cnpj}><td><div className="supplier-name"><span>{supplier.name.slice(0, 2).toUpperCase()}</span><strong>{supplier.name}</strong></div></td><td>{supplier.cnpj}</td><td className="mail-cell">{supplier.contact}</td><td><strong>{supplier.documents}</strong> documentos</td><td><span className={supplier.pendencies ? 'pendency-number' : ''}>{supplier.pendencies}</span></td><td>{supplier.lastUpload}</td><td><StatusBadge status={supplier.status} /></td><td className="menu-cell"><button className="table-action" aria-label={`Ações de ${supplier.name}`} onClick={() => setMenu(menu === supplier.cnpj ? null : supplier.cnpj)}><Ellipsis size={17} /></button>{menu === supplier.cnpj && <div className="row-menu">{['Ver detalhes', 'Ver documentos', 'Reenviar convite', 'Desativar acesso'].map((action) => <button key={action}>{action}</button>)}</div>}</td></tr>)}</tbody></table></div><footer className="table-footer"><span>Mostrando 5 de 128 fornecedores</span><span>Página 1 de 26</span></footer></section>{invite && <div className="modal-backdrop"><section className="modal" role="dialog"><header><span><MailPlus size={18} /></span><div><h2>Convidar fornecedor</h2><p>Envie um acesso seguro ao Portal do Fornecedor.</p></div><button onClick={() => setInvite(false)} aria-label="Fechar"><X size={18} /></button></header><div className="modal__body"><label>Empresa<input defaultValue="Vesuvius Brasil" /></label><label>E-mail do responsável<input defaultValue="fiscal@vesuvius.com.br" /></label></div><footer><Button variant="secondary" onClick={() => setInvite(false)}>Cancelar</Button><Button onClick={() => setInvite(false)}>Enviar convite</Button></footer></section></div>}</div>;
}
